Gate assigner reboot with refresh
vaccfr/CoFrance pull request #7
Opened 2023-04-29 09:16 UTC by goulven04

Re-enable the gate assigner in CoFrance:
- Refresh the gate every 30 seconds
- Add command `.cofrance stand` to disable/enable auto the assigner (enabled by default)
- Add command `.cofrance debug` to display the API queries and responses (disabled by default)

2023-04-30 20:53 UTC, Flox06 commented
@goulven04 we gave a try with Hervé on LFPG tonight, seems that NO query is sent to the server (according to server logs). We tried to toggle enable/disable using .cofrance stand, no changes.
Also enabled debug logs, we didn't see any log.
Need you help :)

2023-04-30 21:00 UTC, Flox06 commented
@goulven04 disregard, I forgot to enable LFPG in the remote config (FACEPALM)
Sorry :p

2023-05-16 02:07 UTC, pierr3 requested changes
@goulven04

2023-05-16 02:07 UTC, pierr3 commented on RadarScreen.cpp
> +				tp_distanceText = tp_distanceText + " " + tp_headingText + "�";
Encoding issue here must be fixed.

2023-05-16 02:07 UTC, pierr3 commented on RadarScreen.cpp
> +					distanceText = distanceText + " " + headingText + "�";
Encoding issue here must be fixed

2023-05-16 10:06 UTC, goulven04 commented on RadarScreen.cpp
> +				tp_distanceText = tp_distanceText + " " + tp_headingText + "�";
Fixed

2023-05-16 10:06 UTC, goulven04 commented on RadarScreen.cpp
> +					distanceText = distanceText + " " + headingText + "�";
Fixed

2023-05-16 15:50 UTC, merged